# Generated by Django 4.1.2 on 2023-10-24 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_category', models.CharField(choices=[('ARIES (33%)', 'ARIES (33%)'), ('Indian Time (60%)', 'Indian Time (60%)'), ('Belgian (7%)', 'Belgian (7%)')], default='Unknown first_name', max_length=100, verbose_name='Proposal Category')),
                ('proposal_title', models.CharField(default='Unknown Proposal_title', max_length=100, verbose_name='Proposal Title')),
                ('proposal_type', models.CharField(choices=[('Long Term (New)', 'Long Term (New)'), ('Long Term (Ongoing)', 'Long Term (Ongoing)'), ('Short Term', 'Short Term'), ('Thesis Project', 'Thesis Project')], default='Unknown first_name', max_length=100, verbose_name='Proposal Type')),
                ('target_opportunity', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Unknown first_name', max_length=100, verbose_name='Target Opportunity')),
                ('co_proposers', models.CharField(default='Unknown first_name', max_length=100, verbose_name='Co-Proposers')),
                ('co_pi', models.CharField(default='Unknown first_name', max_length=100, verbose_name='Co-PI Among Co-Proposers')),
                ('present_ob', models.CharField(default='Unknown first_name', max_length=100, verbose_name='Present OB')),
                ('abstract', models.TextField(default='Unknown first_name', verbose_name='Abstract')),
                ('successful_proposals', models.CharField(choices=[('YES', 'YES'), ('NO', 'NO')], default='Unknown first_name', max_length=100, verbose_name='Successful Proposals')),
                ('scheduling_request', models.CharField(choices=[('Bright', 'Bright'), ('Grey', 'Grey'), ('Dark', 'Dark'), ('Time Critical Observation', 'Time Critical Observation'), ('Other', 'Other')], default='Unknown Scheduling request', max_length=100, verbose_name='Scheduling Request')),
                ('observing_time', models.CharField(blank=True, default='example-3nights', max_length=50, verbose_name='Observing Time')),
                ('preferred_date', models.DateField(blank=True, null=True, verbose_name='Preferred Date')),
                ('impossible_date', models.DateField(blank=True, null=True, verbose_name='Impossible Date')),
                ('justification', models.TextField(default='Unknown first_name', verbose_name='Justification')),
                ('observation_mode', models.CharField(choices=[('Imaging', 'Imaging'), ('Spectroscopy', 'Spectroscopy'), ('Imaging and Spectroscopy', 'Imaging and Spectroscopy')], default='Unknown Observation_Mode', max_length=100, verbose_name='Observation Mode')),
                ('list_of_objects', models.TextField(default='Unknown first_name', verbose_name='List of Objects')),
                ('tech_justify', models.TextField(default='Unknown first_name', verbose_name='Technical Justification')),
                ('plans', models.TextField(default='Unknown first_name', verbose_name='Plans')),
                ('scientific_justify', models.FileField(default='default.jpg', upload_to='scientific_justifications/')),
                ('technical_justify', models.FileField(default='default.jpg', upload_to='technical_justifications/')),
                ('ongoing_proposal_status', models.FileField(default='default.jpg', upload_to='ongoing_proposal_status/')),
                ('previous_obser', models.TextField(default='Unknown first_name', verbose_name='Previous Observation')),
                ('publication_relevant', models.CharField(default='Unknown first_name', max_length=100, verbose_name='Publication relevant')),
                ('publication_list', models.CharField(default='Unknown first_name', max_length=100, verbose_name='Publication list')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userproposal', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
