# Generated by Django 4.1.2 on 2023-10-24 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('1', 'Prof.'), ('2', 'Dr.'), ('3', 'Mrs.'), ('4', 'Ms.'), ('5', 'Mr.')], default='UnKnown Title', max_length=100)),
                ('first_name', models.CharField(default='Unknown first_name', max_length=100)),
                ('last_name', models.CharField(default='Unknown last_name', max_length=100)),
                ('alternate_email_id', models.EmailField(default='user@gmail.com', max_length=100)),
                ('affiliation', models.CharField(choices=[('1', 'test1'), ('2', 'test2'), ('3', 'test3'), ('4', 'test4')], default='Unknown affiliation', max_length=500)),
                ('designation', models.CharField(choices=[('1', 'Faculty/Academic.'), ('2', 'Postdoc.'), ('3', 'PhD student.'), ('4', 'Graduate student.')], default='Unknown designation', max_length=100)),
                ('affiliation_name', models.CharField(default='Unknown affiliation_name', max_length=500)),
                ('research_interest', models.CharField(choices=[('1', 'AGN & Quasars'), ('2', 'Compact Object Binaries'), ('3', 'Cosmology'), ('4', 'Earth Atmosphere'), ('5', 'Exo-solar Planets'), ('6', 'Galaxies'), ('7', 'Gamma Ray Bursts'), ('8', 'Globular Cluster'), ('9', 'High-redshift galaxies'), ('10', 'Individual Star'), ('11', 'Instrumentation'), ('12', 'Intergalactic medium'), ('13', 'Interstellar medium'), ('14', 'Near Earth Objects'), ('15', 'Open Cluster'), ('16', 'Planetary Bodies'), ('17', 'Solar System'), ('18', 'Star and Planet Formation'), ('19', 'Supernovae'), ('20', 'Surveys')], default='Unknown research_interest', max_length=100)),
                ('address', models.CharField(default='Unknown address', max_length=1000)),
                ('telephone_number', models.CharField(default='000000000000000', max_length=15)),
                ('mobile_number', models.CharField(default='0000000000000000', max_length=16)),
                ('country', models.CharField(default='Unknown country', max_length=100)),
                ('state', models.CharField(default='Unknown state', max_length=100)),
                ('city', models.CharField(default='Unknown city', max_length=100)),
                ('act_as_referee', models.CharField(choices=[('1', 'Yes.'), ('2', 'No.')], default='Unknown', max_length=10)),
                ('avatar', models.ImageField(blank=True, default='default.jpg', null=True, upload_to='profile_images')),
                ('bio', models.TextField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
