# Generated by Django 4.1.2 on 2023-10-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='research_interest',
            field=models.CharField(choices=[('1', 'AGN & Quasars'), ('2', 'Compact Object Binaries'), ('3', 'Cosmology'), ('4', 'Earth Atmosphere'), ('5', 'Exo-solar Planets'), ('6', 'Galaxies'), ('7', 'Gamma Ray Bursts'), ('8', 'Globular Cluster'), ('9', 'High-redshift galaxies'), ('10', 'Individual Star'), ('11', 'Instrumentation'), ('12', 'Intergalactic medium'), ('13', 'Interstellar medium'), ('14', 'Near Earth Objects'), ('15', 'Open Cluster'), ('16', 'Planetary Bodies'), ('17', 'Solar System'), ('18', 'Star and Planet Formation'), ('19', 'Supernovae'), ('20', 'Surveys')], max_length=100),
        ),
    ]
