# Generated by Django 4.1.2 on 2023-10-20 09:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('editproposal', '0002_rename_proposal_editedproposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditedProposal',
        ),
    ]
